### ISSUE TITLE
ExtractToDirectory error

### ISSUE THREAD

**Issue by bmdenny** [Zoe-Immersive/SketchfabCSharp#3]
I am getting the following error

Library\PackageCache\com.unity.sketchfab@7a2e8593ed\Runtime\SketchfabModelImporter.cs(86,32): error CS1061: 'ZipArchive' does not contain a definition for 'ExtractToDirectory' and no accessible extension method 'ExtractToDirectory' accepting a first argument of type 'ZipArchive' could be found (are you missing a using directive or an assembly reference?)

**Comment by bmdenny** [comment]
Hi, I have just solved it by following the info here. https://forum.unity.com/threads/c-compression-zip-missing.577492/

[@RWatling](https://forum.unity.com/members/1747420/)

These types are in the System.IO.Compression.FileSystem.dll assembly, which is not passed as a reference by Unity to the C# compiler by default. You can create a file named mcs.rsp in the Assets/ directory of your Unity project to let the C# compiler know you want this additional reference.

The mcs.rsp file should have the following contents:

-r:System.IO.Compression.FileSystem.dll

See the documentation here for more details: https://docs.unity3d.com/Manual/dotnetProfileAssemblies.html

Note that in Unity 2018.3, this file should be renamed to csc.rsp, instead of mcs.rsp.

**Comment by bmdenny** [comment]
Hi Cristian, thanks for reaching out. I was able to solve the problem. Posted the fix on github and closed the issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>



Bruce Denny
Faculty Leader - Digital and Design Technologies

Phone: 07 4796 0222 | <callto:>
Email: ***@***.******@***.***>

[cid:reconciliationemailsig_e6b8723c-5725-4b47-8221-06c2958a9e63.png]

[cid:websitelogo_e1c2c65d-04ac-4e57-948b-a2e4733ec508.jpg]www.ipc.qld.edu.au<http://www.ipc.qld.edu.au> | [cid:003-facebook_d24f9ca7-a723-420c-984f-70263a80112e.png]  Find us on Facebook<https://www.facebook.com/IgnatiusParkCollege/> | [cid:instagram-png-logo-5a3735563a6c74.6993332015135675742393_ccb1a2ff-1d21-4b51-b11c-a417b43ad4fb.jpg]  Find us on Instagram<https://www.instagram.com/ignatiusparkcollege/?utm_source=ig_profile_share&igshid=1hmo05vjfyr9d> | [cid:004-forms_65003333-95ec-4c02-9176-a0455674b0c9.png]  Enrol Online <https://www.ipc.qld.edu.au/enrolment/online-enrolment/> | [cid:001-login_0f6837d5-21c2-4631-ab29-480131b69031.png]  Parent Lounge <https://www.ipc.qld.edu.au/facilities/contact/parent-lounge-login/> | [cid:001-glass-wall_31b4bc37-618c-4225-be34-b7a93541d578.png]  Anti-Bullying Information<https://www.ipc.qld.edu.au/pastoral/anti-bullying-form/>


________________________________
Disclaimer: This email is intended for the use of the named individual or entity and may contain confidential and privileged information. Any dissemination, distribution or copying by anyone other than the intended recipient of this email is strictly prohibited. If this email has been received in error, please send an email in response or telephone the sender immediately, and destroy the original message. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the views of Edmund Rice Education Australia trading as Ignatius Park College and is authorised to do so.



________________________________

**Comment by 4nc3str4l** [comment]
Perfect, thanks to you! 

Let us know if you have any other issues, we will be happy to help :)
