### ISSUE TITLE
I am getting an Unauthorized Request Error

### ISSUE THREAD

**Issue by Shubhra22** [Zoe-Immersive/SketchfabCSharp#4]
So I followed the youtube video from your official channel and got the client ID and secret from sketch fab. But I am getting an unauthorized request error when trying to log in. I can assure that the email and password are correct.

**Comment by 4nc3str4l** [comment]
Hello Shubhra, thanks for reaching out.

May I ask you what is your Unity Version in order to try to reproduce the problem?

Thanks in advance.

**Comment by Shubhra22** [comment]
I m using the unity 2020.3 LTS version.

**Comment by 4nc3str4l** [comment]
Ok I see, I am going to download the version that you mentioned and let you know what I find out. (I currently did the test on a newer version 2021.3.0f1 even though your version should not be a problem)

Meanwhile could you please check if the Client ID and the Client Secret are correct in the SketchfabSettings object? (Maybe they are swapped or there is an extra space or some typo)

I made a quick test and I added an additional letter to either of those and I get unauthorized requests even if the username and passwords are correct in the GetAccessToken method if the API credentials are wrong / swapped... 

For guidance as you can see on the image, the client ID is substantially shorter than the client secret: (Maybe it is trivial but let's try to discard the easy ones in parallel while I have time to download the version and reach back to you as soon as possible)

![Sketchfab_Cred](https://user-images.githubusercontent.com/6674976/177059367-7303c823-285c-4fb4-9433-71ce5ad93f57.PNG)

**Comment by 4nc3str4l** [comment]
Also, something else could be to make sure that the SketchfabSettings object is under a "Resources" folder:

Sketchfab/Resources in our case but any Resources folder should be nice.

**Comment by Shubhra22** [comment]
Thanks for the detailed answer! I actually checked that, but will check it again. My assumption is that probably the redirect link that I provided while app registration need to change or something? I have provided the redirect link as https://joysticklab.com/ which has nothing to do with my app. (It’s my future app website)

**Comment by 4nc3str4l** [comment]
The redirecting link sounds indeed like a good hypothesis It would be great if you could try to disable it and test it again if everything that I mentioned before was correct. 

If the redirecting link is the problem we will ask the users of the wrapper to avoid using it for now until we fix it on our side.

I add this observation to our "to check" list in case it is not possible for you to conduct the test.

Thank you again for your time and consideration as you might have found a bug that might need to be addressed, do not hesitate to write us as soon as you have news.

**Comment by Shubhra22** [comment]
I am not quite sure how can I disable the redirect link. I have looked into the other recommendations and can confirm that everything else was set properly.

**Comment by Shubhra22** [comment]
Hi, I wrote to the sketchfab support team. The grant type they used seems not supported for this plugin. So, now they changed it to the `username/password` grant type, previously it was the `Authorization Code` type. . Now my app is running fine. Thanks for the help.

**Comment by DhiaSendi** [comment]
Hi,
Could you please share the video link/YouTube channel you mentioned?
Thank you!
