### ISSUE TITLE
Not able to find Artist and License Details

### ISSUE THREAD

**Issue by bittu97** [Zoe-Immersive/SketchfabCSharp#8]
Hi there,
While talking with Sketchfab support, they said not to forget to give the credits to the artist and mention the license in your game while using the models from Sketchfab. I can get the name, description and some info for the model but I can't find the information related to the Artist/Author and the license. Can you please help me out?
<img width="439" alt="Screenshot 2023-03-15 at 10 22 39 AM" src="https://user-images.githubusercontent.com/35596213/226106467-a7bd1eb7-226f-4fb1-9cdc-2516d9e23c5d.png">

**Comment by Krohmium** [comment]
I added a pull request that tries to get the license data.

**Comment by 4nc3str4l** [comment]
Merged and released! Thankyou so much @Krohmium :)
